"""add_video_summary

Revision ID: 13e612a76d00
Revises: d49b2a9dbcad
Create Date: 2025-11-17 15:20:43.792476
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13e612a76d00'
down_revision = 'd49b2a9dbcad'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('summary', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video', 'summary')
    # ### end Alembic commands ###

